### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'home/databases/vironomy/vironomy_database//vironomy_database/Genus_single_copy_marker_database.csv'

### ISSUE THREAD

**Issue by Choaro** [b-tierney/vironomy#1]
I successfully installed vironomy and downloaded the database.

Here is the database list:

`
full_sc_marker_db.csv
genbank_pfam_tgirfam_all_annotations_sc.txt
genbank_predicted_proteins.faa
group_taxid_contigid_mapping_annotation_data.tsv
single_copy_marker_database.csv
single_copy_marker_db.hmm
`

I have one fasta file with alll the viral contigs from virsorter2

when I run:

`vironomy end_to_end -i Final-dvf-vs-viral_95.fasta -e 1e-5 -d home/databases/vironomy/vironomy_database//vironomy_database -p 20`

I get this error message:

`(vironomy) [choaro@marvin vironomy_database]$ vironomy end_to_end -i Final-dvf-vs-viral_95.fasta -e 1e-5 -d home/databases/vironomy/vironomy_database//vironomy_database -p 20
Loading reference matrix
Traceback (most recent call last):
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/bin/vironomy", line 207, in <module>
    main()
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/bin/vironomy", line 204, in main
    cli()
  File "/home/choaro/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/choaro/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/choaro/.local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/choaro/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/choaro/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/choaro/.local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/bin/vironomy", line 191, in end_to_end
    markermatrix,distances = ctx.invoke(classify,inputs = inputs,hmmdb = hmmdb, multicopy = multicopy,force = force,taxonomiclevel=taxonomiclevel,dbdir = dbdir,outputdir = outputdir,hitstoreport = hitstoreport,subcluster = subcluster,evaluecutoff = evaluecutoff,threads = threads,tmpdir = tmpdir)
  File "/home/choaro/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/bin/vironomy", line 65, in classify
    data = queryset(hmmdb=hmmdb,fastafile = inputs,taxonomiclevel=taxonomiclevel,multicopy = multicopystatus,hitstoreport = hitstoreport,subcluster = subcluster,fulldb = fulldb,markermatrixref = markermatrixref,taxmapping = taxmap,hmmpath = hmmpath,threads = threads,evaluecutoff = evaluecutoff,tmpdir = tmpdir,outputdir = outputdir)
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/lib/python3.9/site-packages/vironomy/classify.py", line 21, in __init__
    self.referencedbs, self.taxmap = import_reference_dbs(markermatrixref,taxmapping)
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/lib/python3.9/site-packages/vironomy/utils.py", line 17, in import_reference_dbs
    markers = pd.read_csv(markermatrixref,index_col=0)
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 934, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1218, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/lib/python3.9/site-packages/pandas/io/common.py", line 786, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'home/databases/vironomy/vironomy_database//vironomy_database/Genus_single_copy_marker_database.csv'`

Can you please assist?

**Comment by b-tierney** [comment]
Ah I recently changed the database, pushed some code, but haven’t  fixed the remote db version. Will update and inform you when it’s done.

**Comment by b-tierney** [comment]
Give it a try now?

**Comment by Choaro** [comment]
I tried downloaded the database and I got this error:

`(vironomy) [choaro@marvin vironomy]$ vironomy download_db -p /home/databases/vironomy/
Downloading and untarring databases...
--2023-05-18 14:02:12--  https://s3.us-east-1.wasabisys.com/vironomy-databases/vironomy_database.tar.gz
Resolving s3.us-east-1.wasabisys.com (s3.us-east-1.wasabisys.com)... 38.27.106.30, 38.27.106.22, 38.27.106.107, ...
Connecting to s3.us-east-1.wasabisys.com (s3.us-east-1.wasabisys.com)|38.27.106.30|:443... connected.
GnuTLS: Error in the pull function.
Unable to establish SSL connection.
tar (child): /home/databases/vironomy//vironomy_database.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Databases have been downloaded and unpacked. When you run vironomy, write your dbdir path as:

 /home/databases/vironomy//vironomy_database
`

Then I rerun the vironomy and i got the same error:

`(vironomy) [choaro@marvin viral_host]$ vironomy end_to_end -i Final-dvf-vs-viral_95.fasta -e 1e-5 -d home/databases/vironomy/vironomy_database//vironomy_database -p 20
Loading reference matrix
Traceback (most recent call last):
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/bin/vironomy", line 207, in <module>
    main()
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/bin/vironomy", line 204, in main
    cli()
  File "/home/choaro/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/choaro/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/choaro/.local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/choaro/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/choaro/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/choaro/.local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/bin/vironomy", line 191, in end_to_end
    markermatrix,distances = ctx.invoke(classify,inputs = inputs,hmmdb = hmmdb, multicopy = multicopy,force = force,taxonomiclevel=taxonomiclevel,dbdir = dbdir,outputdir = outputdir,hitstoreport = hitstoreport,subcluster = subcluster,evaluecutoff = evaluecutoff,threads = threads,tmpdir = tmpdir)
  File "/home/choaro/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/bin/vironomy", line 65, in classify
    data = queryset(hmmdb=hmmdb,fastafile = inputs,taxonomiclevel=taxonomiclevel,multicopy = multicopystatus,hitstoreport = hitstoreport,subcluster = subcluster,fulldb = fulldb,markermatrixref = markermatrixref,taxmapping = taxmap,hmmpath = hmmpath,threads = threads,evaluecutoff = evaluecutoff,tmpdir = tmpdir,outputdir = outputdir)
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/lib/python3.9/site-packages/vironomy/classify.py", line 21, in __init__
    self.referencedbs, self.taxmap = import_reference_dbs(markermatrixref,taxmapping)
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/lib/python3.9/site-packages/vironomy/utils.py", line 17, in import_reference_dbs
    markers = pd.read_csv(markermatrixref,index_col=0)
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 934, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1218, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/lib/python3.9/site-packages/pandas/io/common.py", line 786, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'home/databases/vironomy/vironomy_database//vironomy_database/Genus_single_copy_marker_database.csv'
`

**Comment by b-tierney** [comment]
Try downloading again? Seems like it was a permissions issue with the new update.

**Comment by Choaro** [comment]
Still getting the same error:
`(vironomy) [choaro@marvin vironomy]$ vironomy download_db -p ./
Downloading and untarring databases...
--2023-07-06 10:12:09--  https://s3.us-east-1.wasabisys.com/vironomy-databases/vironomy_database.tar.gz
Resolving s3.us-east-1.wasabisys.com (s3.us-east-1.wasabisys.com)... 38.27.106.15, 38.27.106.107, 38.27.106.102, ...
Connecting to s3.us-east-1.wasabisys.com (s3.us-east-1.wasabisys.com)|38.27.106.15|:443... connected.
GnuTLS: Error in the pull function.
Unable to establish SSL connection.
tar (child): .//vironomy_database.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Databases have been downloaded and unpacked. When you run vironomy, write your dbdir path as:

 .//vironomy_database`

`Loading reference matrix
Traceback (most recent call last):
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/bin/vironomy", line 207, in <module>
    main()
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/bin/vironomy", line 204, in main
    cli()
  File "/home/choaro/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/choaro/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/choaro/.local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/choaro/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/choaro/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/bin/vironomy", line 65, in classify
    data = queryset(hmmdb=hmmdb,fastafile = inputs,taxonomiclevel=taxonomiclevel,multicopy = multicopystatus,hitstoreport = hitstoreport,subcluster = subcluster,fulldb = fulldb,markermatrixref = markermatrixref,taxmapping = taxmap,hmmpath = hmmpath,threads = threads,evaluecutoff = evaluecutoff,tmpdir = tmpdir,outputdir = outputdir)
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/lib/python3.9/site-packages/vironomy/classify.py", line 21, in __init__
    self.referencedbs, self.taxmap = import_reference_dbs(markermatrixref,taxmapping)
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/lib/python3.9/site-packages/vironomy/utils.py", line 17, in import_reference_dbs
    markers = pd.read_csv(markermatrixref,index_col=0)
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 934, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1218, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/home/choaro/.conda/envs/mamba/envs/vironomy/lib/python3.9/site-packages/pandas/io/common.py", line 786, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/databases/vironomy//Genus_single_copy_marker_database.csv'`
